name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug working directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing contents of the directory:"
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install --upgrade pip
          pip install -r ./requirements.txt  # Ensure correct path

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest
